%% Parameters
env_parameters = struct('NEIGHBOR_THRESHOLD', 0.5, ... % 100.0, ...        % Geo-I Neighbor distance threshold
                        'LR_LOC_SIZE', 20, ...
                        'OBF_RANGE', 4.0, ...
                        'NR_TASK', 50, ...                                  % Number of tasks
                        'EPSILON', 10.0, ...                                % Privacy budget epsilon
                        'GAMMA', 20.0, ...                                  % Relevant location distance threshold: default 20
                        'NR_USER', 10, ...
                        'LR_SAMPLE_SIZE', 100, ...
                        'deg', 3, ...                                       % ??Michael, degree of Polynomial fit    % or 2, 4, …    
                        'NUM_CENTRES', 25, ...                              % ??Michael, for RBF fit                 % try 9, 16, 25 … larger ⇒ more flexible, slower
                        'rank_r', 5, ...                                    % ??Michael, for Low-Rank SVD            % tweak 3–8 for your grid size
                        'nr_loc_selected', 100, ...                         % 
                        'longitude_min', 0, ...                             % 
                        'longitude_max', 0, ...
                        'latitude_min', 0, ...
                        'latitude_max', 0, ...
                        'node_target', [], ...
                        'node_target_selected', [], ...
                        'scale', 1.0, ...
                        'G', [], ...
                        'G_mDP', [], ...
                        'longitude_raw', [], ...
                        'latitude_raw', [], ...
                        'longitude', [], ...
                        'latitude', [], ...
                        'longitude_selected', [], ...
                        'latitude_selected', [], ...
                        'osmid', []); 